### ISSUE TITLE
Add support for mutable collections

### ISSUE THREAD

**Issue by jayasuryat** [jayasuryat/dowel#22]
While exploring solution for #19, I realised there is no support for **Immutable Collections** (`MutableList<*>`, `MutableSet<*>`, `MutableMap<*,*>`)

---

### TODO
- [x] Add support for `MutableList<*>`
- [x] Add support for `MutableSet<*>`
- [x] Add support for `MutableMap<*, *>`
- [x] Update tests
- [x] Update docs
