### ISSUE TITLE
Handle absence of no-args constructor for `@ConsiderForDowel`

### ISSUE THREAD

**Issue by jayasuryat** [jayasuryat/dowel#4]
Currently `DowelGenerator` is not considering if the class annotated with `@ConsiderForDowel` has a no-args constructor or not. It just assumes such a constructor exists and generates code which tries to invoke a (non-existent) no-args constructor. [See here](https://github.com/jayasuryat/dowel/blob/01b7077df93456ffd435414d774cabb96d86ad45/dowel-processor/src/main/java/com/jayasuryat/dowel/processor/generator/DowelGenerator.kt#L176).

`DowelGenerator` should handle such cases gracefully and log meaningful errors.

### TODO

- [x] Remove strict reliance on the `primary constructor` of the class annotated with `@ConsiderForDowel` annotation for object creation. [Read more here](https://github.com/jayasuryat/dowel/issues/4#issuecomment-1272585188).
- [x] Log error for absence of non-private constructors separately.
- [x] Log error for absence of no-args constructors separately.
- [x] Update processor `tests` for the changes
- [x] Update `lint rules` to handle these cases
- [x] Update `lint rule` `tests` for the changes

**Comment by jayasuryat** [comment]
Also, `Dowel` only _considers_ the primary constructor of the classes annotated with `@ConsiderForDowel` annotation. This limitation is not really necessary. All `Dowel` cares about is being able to create an instance by calling the invoke method (i.e., `()` ex `Provider()`) without passing any parameters. It does not really matter if the corresponding  constructor  is primary or not, or wether it has default values or not.

So in light of this issue, it would also make sense to lift of this unnecessary limitation
