### ISSUE TITLE
Classes with no-args-constructor or all-default-values-constructor need not to be annotated with @Dowel

### ISSUE THREAD

**Issue by jayasuryat** [jayasuryat/dowel#9]
## What?

Properties of types having a no-args constructor or if all of the properties of a constructor have default values, then there is no need to annotate those class with `@Dowel` annotation or provide a custom `PreviewParameterProvider` via `@ConsiderForDowel`, as those class's instance could be easily created by invoking a no-args constructor.

For example : 

```kotlin
@Dowel
data class Article(
    val title: String,
    val story: String,
    val type: Type,
    val meta: MetaData,
) {

    data class Type(
        val genre: String = "news",
    )

    class MetaData {
        var hasAffiliateLinks: Boolean = false
    }
}
```

As of now, it is an error to have models like this. It is necessary that both `Type` and `MetaData` classes be annotated with `@Dowel` annotation for `Dowel` to work.

But it is not really necessary, instances of both `Type` and `MetaData` classes can be created without any computational overhead, simply by invoking a no-args constructor (like `Type()` or `MetaData()`).

## How?
This should be pretty straightforward to achieve given they way [`ClassRepresentation`](https://github.com/jayasuryat/dowel/blob/e9ef9e49040b91b75b4a6c81f75614ee49a93ccb/dowel-processor/src/main/java/com/jayasuryat/dowel/processor/model/ClassRepresentation.kt#L41) is structured.

A new type under [`ParameterSpec`](https://github.com/jayasuryat/dowel/blob/e9ef9e49040b91b75b4a6c81f75614ee49a93ccb/dowel-processor/src/main/java/com/jayasuryat/dowel/processor/model/ClassRepresentation.kt#L56) could be added for such no-args-constructor declarations. Given that `ParameterSpec` is a sealed type, the `Kotlin` compiler itself should yell until all of the cases are handled. And the object construction logic should be straightforward as well as classes can be just instantiated with `()`.

## TODO
- [x] Add a new type under `ParameterSpec` for no-args-constructor declarations
- [x] Handle `ClassRepresentation` mapping
- [x] Handle object creation logic
- [x] Add tests 
- [ ] Update documentation
